export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const PASSWORD_FORGOT = "PASSWORD_FORGOT";
export const PASSWORD_RESET = "PASSWORD_RESET";

export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_USER_POSTS = "GET_USER_POSTS";
